### ISSUE TITLE
[Question] What is included?

### ISSUE THREAD

**Issue by alpham8** [tarlepp/symfony-flex-backend#12]
Hi,

thank you for that awesome example project.

I would like to know, what is exactly inlcuded?

Also, this project seems to be huge. What are the really basics I need for an JSON REST API with user management?

Thanks in advice :-)

**Comment by tarlepp** [comment]
Yeah, I should document main features to [README.MD](README.MD) and yes this project has grown quite bit. Below is small list of features that this project contains:

- Role based REST actions
- User, User Group, Role and ApiKey structure
- Authentication by JWT or ApiKey
- Swagger documentation of each REST resource
- Exception listener to convert all exceptions to JSON response
- DTO use with FormTypes
- Multiple console commands; [Commands](https://github.com/tarlepp/symfony-flex-backend#commands)
- Parallel testing within fastest library
- Request/response logger
- Possible to attach lifecycle methods to each resource to do eg. data ACL

Base structure with those REST controllers is `Controller` <--> `Resource` <--> `Repository` <--> `Entity`, so with this stucture is quite easy to keep your controllers as thin as possible.

I hope this cleared something out?

Also note that there is another ways todo REST with Symfony eg. api-platform and fos rest bundle.

**Comment by tarlepp** [comment]
@alpham8 did that answer your questions?

**Comment by alpham8** [comment]
Thank you very much, that answered my question. I'm sorry for being late,
