### ISSUE TITLE
[Question] REST Trait and composer update question

### ISSUE THREAD

**Issue by OGProgrammer** [tarlepp/symfony-flex-backend#13]
Hello @tarlepp - thank you for the amazing project.

*Overview of problem*

I'm using the REST Traits but upon POSTing a new record in (hitting the createAction) throws an HttpException but only after displaying this deprecated message `User Deprecated: Doctrine\Common\ClassLoader is deprecated.` - after that message/exception, then I see this exception:

```
exception:
      class: Symfony\Component\Debug\Exception\FatalThrowableError
      message: 'Argument 3 passed to Symfony\Component\HttpKernel\Exception\HttpException::__construct() must be an instance of Exception or null, instance of TypeError given, called in /var/www/symfony/src/Rest/Traits/RestMethodHelper.php on line 289'
      code: 0
      file: /var/www/symfony/vendor/symfony/http-kernel/Exception/HttpException.php
      line: 24
      trace: "#0 /var/www/symfony/src/Rest/Traits/RestMethodHelper.php(289): Symfony\\Component\\HttpKernel\\Exception\\HttpException->__construct(400, 'Return value of...', Object(TypeError), Array, 400)\n#1 /var/www/symfony/src/Rest/Traits/RestMethodHelper.php(190): App\\Rest\\Controller->determineOutputAndStatusCodeForRestMethodException(Object(TypeError))\n#2 /var/www/symfony/src/Rest/Traits/Methods/CreateMethod.php(61): App\\Rest\\Controller->handleRestMethodException(Object(TypeError))\n#3 /var/www/symfony/src/Rest/Traits/Actions/User/CreateAction.php(60): App\\Controller\\MyCustomController->createMethod(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\Form\\FormFactory))\n#4 /var/www/symfony/vendor/symfony/http-kernel/HttpKernel.php(149): App\\Controller\\MyCustomController->createAction(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\Form\\FormFactory))\n#5 /var/www/symfony/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /var/www/symfony/vendor/symfony/http-kernel/Kernel.php(188): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /var/www/symfony/public/index.php(66): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#8 {main}"
```

Some quick research pointed me to replacing doctrine/common with the individual packages needed but something tells me this isn't right. Although I've tried updating dependencies and had no luck there either.

*My Environment*

I'm using a docker environment (which is slightly tweaked from this repo https://github.com/eko/docker-symfony - I replaced the fpm container with this https://gist.github.com/OGProgrammer/f143b2b0c889c67f512f757cdcdbcbc3 ) and I'm running PHP 7.2.8 

*Questions*

* 1st Question - Is there something I'm missing about using these Traits? I'm debating ditching them and just writing the routes by hand in my controller as another route I wrote works inside the controller just fine.

* 2nd Question - Running composer update throws an error also once I hit the `phpstan` section. I tried bumping my memory limit up cause that was my first problem I ran into but then hit this:

```
Changed current directory to vendor-bin/phpstan
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
Script @composer bin all update --ansi handling the post-update-cmd event returned with error code 137
```

Anything special needed for a composer/update?

Thank you and let me know if I can provide any more detail.

**Comment by OGProgrammer** [comment]
As far as the composer issue, was able to get around that by doing the following before installing/updating composer

```
export COMPOSER_PROCESS_TIMEOUT=2000
export COMPOSER_MEMORY_LIMIT=-1
composer require ywh/doctrine-encryption-bundle
```

**Comment by tarlepp** [comment]
Haven't seen either of those questions to happen in projects where I'm using this _boilerplate_

But for the 1st it seems like your form is having `TypeError` - you need to debug that a bit deeper.

And for the 2nd that seems like some kind of docker environment problem - or something else because you're requiring `composer require ywh/doctrine-encryption-bundle` which is not used with this repository at all.
