### ISSUE TITLE
[Question] Composer install for Production

### ISSUE THREAD

**Issue by OGProgrammer** [tarlepp/symfony-flex-backend#14]
Hey @tarlepp,

Started trying to deploy this to my production environment and run into some issues with `composer install --no-dev` 

It looks like you have some scripts that run which require some of the binaries from the `require-dev` dependancies. Wondering if you've used this in production and if so, what you do for composer builds.

Specifically the security checker and the requirements-checker were not there when installing without composer dependancies. Before I start messing with this too much, wanted to see your thoughts.

Thanks!

**Comment by tarlepp** [comment]
actually that is know problem, and haven't had time to fix that one. Noticed that same couple of months ago @work, but didn't have time to fix that - and basically forgot that...

If you've time to make PR it would be really nice.

**Comment by OGProgrammer** [comment]
Cool, I'll see if I can find a good solution :)

**Comment by OGProgrammer** [comment]
https://github.com/neronmoon/scriptsdev Looks interesting.

Something like this might work too but Dotenv is being a pain...

```
"scripts": {
    "post-install-cmd": [
        "[ $COMPOSER_DEV_MODE -eq 0 ] || echo devmode only"
    ]
},
```
I'll look into this more next week.

**Comment by tarlepp** [comment]
Current `composer.json` should have fix for this - https://github.com/tarlepp/symfony-flex-backend/blob/master/composer.json#L103
