### ISSUE TITLE
Help me please, I can not do à Post Request for a new make:rest-api resource

### ISSUE THREAD

**Issue by judileroi** [tarlepp/symfony-flex-backend#16]
Hello, 
Thank you for your Code, Please help me i install the app and i do ./bin/console make:rest-api to create All of things for a Category Entity. So when i try in PostMan GET is Good but POST i have an error suc as 

{
    "message": "Argument 3 passed to Symfony\\Component\\HttpKernel\\Exception\\HttpException::__construct() must be an instance of Exception or null, instance of TypeError given, called in /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php on line 288",
    "code": 0,
    "status": 500,
    "debug": {
        "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
        "file": "/Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/Exception/HttpException.php",
        "line": 24,
        "message": "Argument 3 passed to Symfony\\Component\\HttpKernel\\Exception\\HttpException::__construct() must be an instance of Exception or null, instance of TypeError given, called in /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php on line 288",
        "trace": [
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php",
                "line": 288,
                "function": "__construct",
                "class": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
                "type": "->",
                "args": [
                    400,
                    "Return value of App\\Rest\\RestResource::getFormTypeClass() must be of the type string, null returned",
                    {},
                    [],
                    400
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php",
                "line": 189,
                "function": "determineOutputAndStatusCodeForRestMethodException",
                "class": "App\\Rest\\Controller",
                "type": "->",
                "args": [
                    {}
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/Methods/CreateMethod.php",
                "line": 61,
                "function": "handleRestMethodException",
                "class": "App\\Rest\\Controller",
                "type": "->",
                "args": [
                    {}
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/Actions/User/CreateAction.php",
                "line": 60,
                "function": "createMethod",
                "class": "App\\Controller\\TestController",
                "type": "->",
                "args": [
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    },
                    {}
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/HttpKernel.php",
                "line": 149,
                "function": "createAction",
                "class": "App\\Controller\\TestController",
                "type": "->",
                "args": [
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    },
                    {}
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/HttpKernel.php",
                "line": 66,
                "function": "handleRaw",
                "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                "type": "->",
                "args": [
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    },
                    1
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/Kernel.php",
                "line": 188,
                "function": "handle",
                "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                "type": "->",
                "args": [
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    },
                    1,
                    true
                ]
            },
            {
                "file": "/Users/TANDJIEKPON/Sites/soccerDev/public/index.php",
                "line": 71,
                "function": "handle",
                "class": "Symfony\\Component\\HttpKernel\\Kernel",
                "type": "->",
                "args": [
                    {
                        "attributes": {},
                        "request": {},
                        "query": {},
                        "server": {},
                        "files": {},
                        "cookies": {},
                        "headers": {}
                    }
                ]
            }
        ],
        "traceString": "#0 /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php(288): Symfony\\Component\\HttpKernel\\Exception\\HttpException->__construct(400, 'Return value of...', Object(TypeError), Array, 400)\n#1 /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/RestMethodHelper.php(189): App\\Rest\\Controller->determineOutputAndStatusCodeForRestMethodException(Object(TypeError))\n#2 /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/Methods/CreateMethod.php(61): App\\Rest\\Controller->handleRestMethodException(Object(TypeError))\n#3 /Users/TANDJIEKPON/Sites/soccerDev/src/Rest/Traits/Actions/User/CreateAction.php(60): App\\Controller\\TestController->createMethod(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\Form\\FormFactory))\n#4 /Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/HttpKernel.php(149): App\\Controller\\TestController->createAction(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\Form\\FormFactory))\n#5 /Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /Users/TANDJIEKPON/Sites/soccerDev/vendor/symfony/http-kernel/Kernel.php(188): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /Users/TANDJIEKPON/Sites/soccerDev/public/index.php(71): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#8 {main}"
    }
}

I just want to send {"name":"xxxx"} to populate the table.
Can you help me please

**Comment by tarlepp** [comment]
You're missing the FormType for your resource - that command doesn't create that yet.

**Comment by tarlepp** [comment]
See eg. `UserController` there you have `protected static $formTypes` where you map each method to use some specified FormType

And yes I need to make clearer error about that part.

**Comment by tarlepp** [comment]
@judileroi so you could close this issue then?

**Comment by judileroi** [comment]
Yeah !!
