### ISSUE TITLE
Good but can I have some examples if want to provide web API service with user login and password

### ISSUE THREAD

**Issue by ngkung** [tarlepp/symfony-flex-backend#2]
Any resources/examples that I can make references to build up API services based upon this flex backend?
I am new to Symfony 4, especially flex.
Just simple examples are enough, e.g. remote login, token exchange/management and protected web services.

Thank you so much.

**Comment by tarlepp** [comment]
Examples you can find from `http://localhost/api/doc` url

**Comment by OGProgrammer** [comment]
Using a username and password is easy but I'm struggling with how to authenticate with an api key. Any thoughts?

**Comment by tarlepp** [comment]
By sending `Authorization` header with value `ApiKey _your_api_key_here_`

**Comment by OGProgrammer** [comment]
Heads up that my issue was I've implemented your "Blameable" trait on one of my entities and it was getting updated by an API Key authenticated session which causes an issue in Doctrine unitofwork when trying to get the `user id` from the `ApiKeyUser` class. I suppose this might be brought up by someone else that uses that blameable trait and update/creates an entity via API Auth. User/Pass auth works with the blameable trait with no issues.
