### ISSUE TITLE
Can you add an Example REST  Endpoint (API)  apart from User related ones . 

### ISSUE THREAD

**Issue by yudhir** [tarlepp/symfony-flex-backend#254]
Maybe a generic  Post and Comments and User - Author example . It  would make it even clearer . 

Is it compatible with Maker Bundle OR  an API could be generated with make tool or some generators  as well .

**Comment by yudhir** [comment]
I have added an Endpoint and am getting 
`"An exception occurred while executing 'INSERT INTO app_products (id, brand, name, description, size, sku, material, manufacturer, logo, color, created_at, updated_at, created_by_id, updated_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"\\x11\\xea\\x38\\x9c\\xea\\xdd\\x0c\\x24\\x99\\x23\\x02\\x42\\xac\\x12\\x00\\x03\", null, null, null, null, null, null, null, null, null, \"2020-01-16 20:15:19\", \"2020-01-16 20:15:19\", \"\\x11\\xea\\x37\\xcb\\x48\\xe0\\x95\\xde\\xa1\\xc2\\x02\\x42\\xac\\x12\\x00\\x03\", \"\\x11\\xea\\x37\\xcb\\x48\\xe0\\x95\\xde\\xa1\\xc2\\x02\\x42\\xac\\x12\\x00\\x03\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null",`


```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null

  at src/Rest/Traits/RestMethodHelper.php:188
  at App\Rest\Controller->determineOutputAndStatusCodeForRestMethodException(object(NotNullConstraintViolationException))
     (src/Rest/Traits/RestMethodHelper.php:130)
  at App\Rest\Controller->handleRestMethodException(object(NotNullConstraintViolationException))
     (src/Rest/Traits/Methods/CreateMethod.php:52)
  at App\Controller\ProductController->createMethod(object(Request), object(ProductCreate))
     (src/Rest/Traits/Actions/Admin/CreateAction.php:54)
  at App\Controller\ProductController->createAction(object(Request), object(ProductCreate))
     (vendor/symfony/http-kernel/HttpKernel.php:146)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:63)     
```

it is not reading parameters it seems . 
POST http://127.0.0.1:8000/product , Body is {"name": "Product111","brand":"Brand233"}
]} . name is the only one with not null , no other validation constraints.

**Comment by tarlepp** [comment]
so most likely you don't have necessary DTO class and Automapper class to convert your request. So basically you need to add `DTO` class for that product and then `Automapper` class to convert your request to that DTO.

**Comment by yudhir** [comment]
I created Automapper and DTO  without it i received different exceptions .  Hence I wanted to look at a generic example , not userrelated one . 

The above exception occurs even when sending No Body on POST request. 

The example APIKeyCreate DTO is empty and extends APIKey  . Hence my ProductCreate DTO is also similar and empty . 
On My Mapper , I have mentioned the properties to be mapped too . Commenting it gave a `Exception : need properties to map ..`

**Comment by tarlepp** [comment]
generic example is that `ApiKey` that isn't user related directly - if you're on Symfony Slack ping me there so that we can take closer look of your setup?

**Comment by yudhir** [comment]
pmmed
