### ISSUE TITLE
OK, but incomplete, skipped, or risky tests!

### ISSUE THREAD

**Issue by ngkung** [tarlepp/symfony-flex-backend#3]
I have made a test run and got the following result:
Any idea? I have already tried to delete the test-readable.log and re-test but still failed.
CENTOS 7.4 and PHP 7.2

OK, but incomplete, skipped, or risky tests!
Tests: 1997, Assertions: 4003, Skipped: 46.
PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/symfony-flex/symfony-flex-backend/var/log/test-readable.log" could not be opened: failed to open stream: Too many open files in /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/symfony-flex/symfony-flex-backend/vendor/easycorp/easy-log-handler/src/EasyLogHandler.php(38): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(90): EasyCorp\EasyLog\EasyLogHandler->handleBatch(Array)
#2 /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(106): Monolog\Handler\BufferHandler->flush()
#3 [internal function]: Monolog\Handler\BufferHandler->close()
#4 {main}
  thrown in /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/symfony-flex/symfony-flex-backend/var/log/test-readable.log" could not be opened: failed to open stream: Too many open files in /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/symfony-flex/symfony-flex-backend/vendor/easycorp/easy-log-handler/src/EasyLogHandler.php(38): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(90): EasyCorp\EasyLog\EasyLogHandler->handleBatch(Array)
#2 /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(106): Monolog\Handler\BufferHandler->flush()
#3 [internal function]: Monolog\Handler\BufferHandler->close()
#4 {main}
  thrown in /var/www/symfony-flex/symfony-flex-backend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
make: *** [run-tests] Error 255

**Comment by tarlepp** [comment]
That error is not related to this project. It's your platform problem - see https://stackoverflow.com/questions/14748499/fatal-error-too-many-open-files
