### ISSUE TITLE
Why not using the api-platform recipe?

### ISSUE THREAD

**Issue by mappedinn** [tarlepp/symfony-flex-backend#4]
Good morning,

This is a great work.
 I am wondering why not using api-platform recipe?

Thanks

**Comment by bigpetecz** [comment]
Hi I think its promising and I agree with @mappedinn what about recipe?

**Comment by tarlepp** [comment]
Actually I'm not sure if api-platform will give me clean controllers as this one - and this is not a competition which one is better - I just started to create things and this is what that process made happen.

Although I should take a closer look of that api-platform at somepoint to see what that really offers and what not.

But for the actual question 'why not using api-platform recipe?':
 * wanted to learn symfony more and to have all in my own hands
 * custom parameters eg. `where` with advanced options same with `populate` etc.
 * role based endpoint actions with minimal setup

**Comment by mappedinn** [comment]
Thanks @tarlepp
