### ISSUE TITLE
Api doc generation

### ISSUE THREAD

**Issue by marcinj1** [tarlepp/symfony-flex-backend#5]
Hello, is it possible to put form schema into requests? At this moment I have no informations in api doc what to send when creating new entity.

**Comment by tarlepp** [comment]
That API doc part is not production ready yet - actually it will need some serious work. And actually  exposing dto / form also is really good idea - thanks for that.

I'm trying to get some time to make API doc part more completed one, but I cannot promise anything... But anyway thanks for this issue!

**Comment by marcinj1** [comment]
No problem, I will try to this in my project and make pull request on your repo.

**Comment by tarlepp** [comment]
@marcinj1 any updates?

**Comment by marcinj1** [comment]
Unfortunately no, I abandoned my project which was using your lib.

**Comment by tarlepp** [comment]
ok, closing this then
