### ISSUE TITLE
utf8mb4 gives problems with MySQL

### ISSUE THREAD

**Issue by thecassion** [tarlepp/symfony-flex-backend#6]
`

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key
was t
  oo long; max key length is 767 bytes

In PDOConnection.php line 109:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key
was t
  oo long; max key length is 767 bytes

In PDOConnection.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key
was t
  oo long; max key length is 767 bytes

`

**Comment by tarlepp** [comment]
yep, that is known issue with eg. mariadb 10.1 branch. Solutions for this are following:
1) Upgrade your mariadb / another db
2) start to use plain utf8

Also you need to make sure that you're using correct `serverVersion` on your `DATABASE_URL` parameter.

Example for mariadb 10.1
```
DATABASE_URL=mysql://someuser:somepassword@127.0.0.1:3306/${DATABASE_NAME}?charset=utf8&serverVersion=mariadb-10.1.29
```

Example for mariadb 10.2
```
DATABASE_URL=mysql://someuser:somepassword@127.0.0.1:3306/${DATABASE_NAME}?charset=utf8mb4&serverVersion=mariadb-10.2.14
```

Not really application specified issue - although I should mention this on `README.MD` - Closing issue for now.
