### ISSUE TITLE
NelmioApiDocBundle Twig Controller not found

### ISSUE THREAD

**Issue by christopher2007** [tarlepp/symfony-flex-backend#7]
I downloaded the original code and set it up like descriped in the `README.md`.  
The authentication token are working fine and the routes also behave normal.  
But the routes `/api/doc/` and `/api/doc.json` generate this error:  
  
    {
      "message": "Class twig.controller.preview_error does not exist",
      "code": -1,
      "status": 500,
      "debug": {
        "exception": "ReflectionException",
        "file": "/htdocs/backend/htdocs/src/Rest/Describer/ApiDocDescriber.php",
        "line": 164,
        "message": "Class twig.controller.preview_error does not exist",
        "trace": [
          ...
        ]
      }
    }
  
The `/config/routes/nelmio_api_doc.yaml` is not modified:  
  
    NelmioApiDocBundleUi:
        resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
        prefix:   /api/doc
    
    NelmioApiDocBundle:
        path: /api/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger }
  
What am I missing?  
Or is this a bug in the current state?

**Comment by tarlepp** [comment]
That one is bug on my code - trying to solve that within next days.

**Comment by tarlepp** [comment]
@christopher2007 created quick fix this - thanks for reporting.

**Comment by tarlepp** [comment]
np, if you can confirm that everything works on your side, feel free to close this issue.

**Comment by tarlepp** [comment]
Fixed ECS errors, and the [tests are passing](https://travis-ci.org/tarlepp/symfony-flex-backend/jobs/393082939) now (although though still no coverage - but this is another issue that I  need to solve someway).

**Comment by christopher2007** [comment]
yea, tested it. works great, thx.
