### ISSUE TITLE
[Question] Block login on too many requests

### ISSUE THREAD

**Issue by christopher2007** [tarlepp/symfony-flex-backend#9]
Hi there,  
  
is a feature like this planned in the project?  
Something like  
  
    'failedLogin' => [
        'time_login'  => '10 minutes',     // When a user in this timespan ...
        'count'       => '5',              // ... has this many wrong login attempts, then block him ...
        'time_block'  => '10 minutes',     // ... for this timespan
    ],
  
So that the user can not log in more in the block time.  
I have to implement such a feature in most of the frameworks myself but in the end it is a common thing to do.  
  
All in all a really nice framework you are creating there. I have still problems understanding so much code for such a small feature set, but I am doing my best.  
greeings and have a nice day :)  
  
PS.: sry, but it seems, I can not tag it with the label "question" myself ...

**Comment by tarlepp** [comment]
There is already simply logic for this on this project see https://github.com/tarlepp/symfony-flex-backend/blob/master/src%2FEventSubscriber%2FLockedUserSubscriber.php

**Comment by tarlepp** [comment]
Closing this, because no replies - feel free to re-open if there is something else.
